# Generated by Django 4.0.1 on 2022-05-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('url_id', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='dot_product')),
            ],
        ),
    ]
