# Generated by Django 4.0.1 on 2022-05-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_docker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='img',
            field=models.ImageField(upload_to='docker_product'),
        ),
    ]
